export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_CUSTOMER_BEGIN = "CREATE_CUSTOMER_BEGIN";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";

export const GET_CUSTOMERS_BEGIN = "GET_CUSTOMERS_BEGIN";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";

export const SET_EDIT_CUSTOMER = "SET_EDIT_CUSTOMER";

export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";

export const EDIT_CUSTOMER_BEGIN = "EDIT_CUSTOMER_BEGIN";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_ERROR = "EDIT_CUSTOMER_ERROR";

export const SHOW_STATS_BEGIN = "  SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "  SHOW_STATS_SUCCESS";

export const SHOW_BRANDSTATS_BEGIN = " SHOW_BRANDSTATS_BEGIN";
export const SHOW_BRANDSTATS_SUCCESS = "  SHOW_BRANDSTATS_SUCCESS";

export const CLEAR_FILTERS = "  CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_PAGE_RECORDS = "CHANGE_PAGE_RECORDS";
export const CHANGE_PAGE_SUPPLIER = "CHANGE_PAGE_SUPPLIER";

export const SHOW_MONTHLYINCOME_BEGIN = " SHOW_MONTHLYINCOME_BEGIN";
export const SHOW_MONTHLYINCOME_SUCCESS = "  SHOW_BRANDSTATS_SUCCESS";

export const GET_RECORDS_BEGIN = "GET_RECORDS_BEGIN";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";

export const CREATE_SUPPLIER_BEGIN = "CREATE_SUPPLIER_BEGIN";
export const CREATE_SUPPLIER_ERROR = "CREATE_SUPPLIER_ERROR";
export const CREATE_SUPPLIER_SUCCESS = "CREATE_SUPPLIER_SUCCESS";

export const GET_SUPPLIER_BEGIN = "GET_SUPPLIER_BEGIN";
export const GET_SUPPLIER_SUCCESS = "GET_SUPPLIER_SUCCESS";

export const SET_EDIT_SUPPLIER = "SET_EDIT_SUPPLIER";

export const EDIT_SUPPLIER_BEGIN = "EDIT_SUPPLIER_BEGIN";
export const EDIT_SUPPLIER_SUCCESS = "EDIT_SUPPLIER_SUCCESS";
export const EDIT_SUPPLIER_ERROR = "EDIT_SUPPLIER_ERROR";

export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";

export const GET_CUSTOMERRECEIPT_BEGIN = "GET_CUSTOMERRECEIPT_BEGIN";
export const GET_CUSTOMERRECEIPT_SUCCESS = "GET_CUSTOMERRECEIPT_SUCCESS";
